# Generated by Django 3.1.3 on 2020-11-24 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0002_jd'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resume',
        ),
    ]
